export { default as Footer } from './Footer';
export { default as Layout } from './Layout';
export { default as Navbar } from './Navbar';
export { default as Product } from './Product';
export { default as HeroBanner } from './HeroBanner';
export { default as FooterBanner } from './FooterBanner';
export { default as Cart } from './Cart';
// export { default as Categories } from './Category';
export { default as Category } from './Category';
export { default as SecondBanner } from './SecondBanner';
export { default as Banner } from './Banner';
